
CREATE TABLE Product(
`bleachingCode` DOUBLE,
`defaultLanguage` VARCHAR(100),
`definitionsdetailsData0cedi` VARCHAR(100),
`definitionsdetailsData0childWeightFrom` DOUBLE,
`definitionsdetailsData0childWeightTo` DOUBLE,
`definitionsdetailsData0color_code` DOUBLE,
`definitionsdetailsData0color_description` VARCHAR(100),
`definitionsdetailsData0countryImages` VARCHAR(100),
`definitionsdetailsData0defaultSku` VARCHAR(100),
`definitionsdetailsData0preferredEan` DOUBLE,
`definitionsdetailsData0sapAssortmentLevel` VARCHAR(100),
`definitionsdetailsData0sapPrice` DOUBLE,
`definitionsdetailsData0season` VARCHAR(100),
`definitionsdetailsData0showOnLineSku` VARCHAR(100),
`definitionsdetailsData0size_code` VARCHAR(100),
`definitionsdetailsData0size_description` VARCHAR(100),
`definitionsdetailsData0skuID` DOUBLE,
`definitionsdetailsData0skuName` VARCHAR(100),
`definitionsdetailsData0stateOfArticle` VARCHAR(100),
`definitionsdetailsData0umSAPprice` VARCHAR(100),
`definitionsdetailsData0volume` DOUBLE,
`definitionsdetailsData0weight` DOUBLE,
`definitionsdetailsData1cedi` VARCHAR(100),
`definitionsdetailsData1childWeightFrom` DOUBLE,
`definitionsdetailsData1childWeightTo` DOUBLE,
`definitionsdetailsData1color_code` DOUBLE,
`definitionsdetailsData1color_description` VARCHAR(100),
`definitionsdetailsData1countryImages` VARCHAR(100),
`definitionsdetailsData1defaultSku` VARCHAR(100),
`definitionsdetailsData1preferredEan` DOUBLE,
`definitionsdetailsData1sapAssortmentLevel` VARCHAR(100),
`definitionsdetailsData1sapPrice` DOUBLE,
`definitionsdetailsData1season` VARCHAR(100),
`definitionsdetailsData1showOnLineSku` VARCHAR(100),
`definitionsdetailsData1size_code` VARCHAR(100),
`definitionsdetailsData1size_description` VARCHAR(100),
`definitionsdetailsData1skuID` DOUBLE,
`definitionsdetailsData1skuName` VARCHAR(100),
`definitionsdetailsData1stateOfArticle` VARCHAR(100),
`definitionsdetailsData1umSAPprice` VARCHAR(100),
`definitionsdetailsData1volume` DOUBLE,
`definitionsdetailsData1weight` DOUBLE,
`definitionsdetailsData2cedi` VARCHAR(100),
`definitionsdetailsData2childWeightFrom` DOUBLE,
`definitionsdetailsData2childWeightTo` DOUBLE,
`definitionsdetailsData2color_code` DOUBLE,
`definitionsdetailsData2color_description` VARCHAR(100),
`definitionsdetailsData2countryImages` VARCHAR(100),
`definitionsdetailsData2defaultSku` VARCHAR(100),
`definitionsdetailsData2preferredEan` DOUBLE,
`definitionsdetailsData2sapAssortmentLevel` VARCHAR(100),
`definitionsdetailsData2sapPrice` DOUBLE,
`definitionsdetailsData2season` VARCHAR(100),
`definitionsdetailsData2showOnLineSku` VARCHAR(100),
`definitionsdetailsData2size_code` VARCHAR(100),
`definitionsdetailsData2size_description` VARCHAR(100),
`definitionsdetailsData2skuID` DOUBLE,
`definitionsdetailsData2skuName` VARCHAR(100),
`definitionsdetailsData2stateOfArticle` VARCHAR(100),
`definitionsdetailsData2umSAPprice` VARCHAR(100),
`definitionsdetailsData2volume` DOUBLE,
`definitionsdetailsData2weight` DOUBLE,
`definitionsdetailsData3cedi` VARCHAR(100),
`definitionsdetailsData3childWeightFrom` DOUBLE,
`definitionsdetailsData3childWeightTo` DOUBLE,
`definitionsdetailsData3color_code` DOUBLE,
`definitionsdetailsData3color_description` VARCHAR(100),
`definitionsdetailsData3countryImages` VARCHAR(100),
`definitionsdetailsData3defaultSku` VARCHAR(100),
`definitionsdetailsData3preferredEan` DOUBLE,
`definitionsdetailsData3sapAssortmentLevel` VARCHAR(100),
`definitionsdetailsData3sapPrice` DOUBLE,
`definitionsdetailsData3season` VARCHAR(100),
`definitionsdetailsData3showOnLineSku` VARCHAR(100),
`definitionsdetailsData3size_code` VARCHAR(100),
`definitionsdetailsData3size_description` VARCHAR(100),
`definitionsdetailsData3skuID` DOUBLE,
`definitionsdetailsData3skuName` VARCHAR(100),
`definitionsdetailsData3stateOfArticle` VARCHAR(100),
`definitionsdetailsData3umSAPprice` VARCHAR(100),
`definitionsdetailsData3volume` DOUBLE,
`definitionsdetailsData3weight` DOUBLE,
`definitionsheaderDatabag` VARCHAR(100),
`definitionsheaderDatableachingDescription` VARCHAR(100),
`definitionsheaderDatabrand` VARCHAR(100),
`definitionsheaderDatabrandCode` DOUBLE,
`definitionsheaderDatacatalog` VARCHAR(100),
`definitionsheaderDatacomposition` VARCHAR(100),
`definitionsheaderDatacreationDateInDatabase` VARCHAR(100),
`definitionsheaderDatacustom1` VARCHAR(100),
`definitionsheaderDatacustom2` VARCHAR(100),
`definitionsheaderDatacustom3` VARCHAR(100),
`definitionsheaderDatadrinkHolder` VARCHAR(100),
`definitionsheaderDatadryCleaningDescription` VARCHAR(100),
`definitionsheaderDatadryingDescription` VARCHAR(100),
`definitionsheaderDataEShopDisplayName` VARCHAR(100),
`definitionsheaderDataEShopLongDescription` VARCHAR(100),
`definitionsheaderDataergonomicSeat` VARCHAR(100),
`definitionsheaderDatafasteningTypeDescription` VARCHAR(100),
`definitionsheaderDatafasteningTypeTextile` VARCHAR(100),
`definitionsheaderDataflat` VARCHAR(100),
`definitionsheaderDatafreeDelivery` VARCHAR(100),
`definitionsheaderDatagender` VARCHAR(100),
`definitionsheaderDataindicatorOfItHasToBeAssembled` VARCHAR(100),
`definitionsheaderDataironingDescription` VARCHAR(100),
`definitionsheaderDatalastDateChanged` VARCHAR(100),
`definitionsheaderDatalastUserChanged` VARCHAR(100),
`definitionsheaderDataproductFeatures0` VARCHAR(100),
`definitionsheaderDataproductFeatures1` VARCHAR(100),
`definitionsheaderDataproductMissingFeatures0` VARCHAR(100),
`definitionsheaderDataproductMissingFeatures1` VARCHAR(100),
`definitionsheaderDataproductStatus` VARCHAR(100),
`definitionsheaderDatapulloutType` VARCHAR(100),
`definitionsheaderDatapulloutTypeDescription` VARCHAR(100),
`definitionsheaderDatapunnet` VARCHAR(100),
`definitionsheaderDatasapCategoryID` DOUBLE,
`definitionsheaderDatasapCategoryName` VARCHAR(100),
`definitionsheaderDatasapDivisionID` DOUBLE,
`definitionsheaderDatasapDivisionName` VARCHAR(100),
`definitionsheaderDatasapFamilyDescription` VARCHAR(100),
`definitionsheaderDatasapFamilyID` DOUBLE,
`definitionsheaderDatasapFamilyName` VARCHAR(100),
`definitionsheaderDatasapMacrocategoryID` VARCHAR(100),
`definitionsheaderDatasapMacrocategoryName` VARCHAR(100),
`definitionsheaderDatasapName` VARCHAR(100),
`definitionsheaderDatasapUniverseID` VARCHAR(100),
`definitionsheaderDatasapUniverseName` VARCHAR(100),
`definitionsheaderDatashowOnLine` VARCHAR(100),
`definitionsheaderDatasizeGuide` VARCHAR(100),
`definitionsheaderDatasourceID` VARCHAR(100),
`definitionsheaderDatauserOfCreation` VARCHAR(100),
`definitionsheaderDatawaistlineDescription` VARCHAR(100),
`definitionsheaderDatawashability` VARCHAR(100),
`definitionsheaderDatawashabilityDescription` VARCHAR(100),
`definitionsheaderDatazipStopper` VARCHAR(100),
`definitionslocale` VARCHAR(100),
`dryCleaningCode` DOUBLE,
`dryingCode` DOUBLE,
`fasteningTypeCode` DOUBLE,
`ironingCode` DOUBLE,
`productID` DOUBLE,
`pulloutTypeCode` DOUBLE,
`sapPacket` DOUBLE,
`updateImages` VARCHAR(100),
`waistlineCode` DOUBLE,
`washabilityCode` DOUBLE
);


INSERT INTO Product(`bleachingCode`, `defaultLanguage`, `definitionsdetailsData0cedi`, `definitionsdetailsData0childWeightFrom`,
 `definitionsdetailsData0childWeightTo`, `definitionsdetailsData0color_code`, `definitionsdetailsData0color_description`, 
 `definitionsdetailsData0countryImages`, `definitionsdetailsData0defaultSku`, `definitionsdetailsData0preferredEan`, 
 `definitionsdetailsData0sapAssortmentLevel`, `definitionsdetailsData0sapPrice`, `definitionsdetailsData0season`, 
 `definitionsdetailsData0showOnLineSku`, `definitionsdetailsData0size_code`, `definitionsdetailsData0size_description`,
  `definitionsdetailsData0skuID`, `definitionsdetailsData0skuName`, `definitionsdetailsData0stateOfArticle`, 
  `definitionsdetailsData0umSAPprice`, `definitionsdetailsData0volume`, `definitionsdetailsData0weight`, `definitionsdetailsData1cedi`, 
  `definitionsdetailsData1childWeightFrom`, `definitionsdetailsData1childWeightTo`, `definitionsdetailsData1color_code`, 
  `definitionsdetailsData1color_description`, `definitionsdetailsData1countryImages`, `definitionsdetailsData1defaultSku`,
   `definitionsdetailsData1preferredEan`, `definitionsdetailsData1sapAssortmentLevel`, `definitionsdetailsData1sapPrice`, 
   `definitionsdetailsData1season`, `definitionsdetailsData1showOnLineSku`, `definitionsdetailsData1size_code`,
    `definitionsdetailsData1size_description`, `definitionsdetailsData1skuID`, `definitionsdetailsData1skuName`, 
    `definitionsdetailsData1stateOfArticle`, `definitionsdetailsData1umSAPprice`, `definitionsdetailsData1volume`,
     `definitionsdetailsData1weight`, `definitionsdetailsData2cedi`, `definitionsdetailsData2childWeightFrom`, 
     `definitionsdetailsData2childWeightTo`, `definitionsdetailsData2color_code`, `definitionsdetailsData2color_description`,
      `definitionsdetailsData2countryImages`, `definitionsdetailsData2defaultSku`, `definitionsdetailsData2preferredEan`,
       `definitionsdetailsData2sapAssortmentLevel`, `definitionsdetailsData2sapPrice`, `definitionsdetailsData2season`,
        `definitionsdetailsData2showOnLineSku`, `definitionsdetailsData2size_code`, `definitionsdetailsData2size_description`, 
        `definitionsdetailsData2skuID`, `definitionsdetailsData2skuName`, `definitionsdetailsData2stateOfArticle`, 
        `definitionsdetailsData2umSAPprice`, `definitionsdetailsData2volume`, `definitionsdetailsData2weight`,
         `definitionsdetailsData3cedi`, `definitionsdetailsData3childWeightFrom`, `definitionsdetailsData3childWeightTo`,
          `definitionsdetailsData3color_code`, `definitionsdetailsData3color_description`, `definitionsdetailsData3countryImages`,
           `definitionsdetailsData3defaultSku`, `definitionsdetailsData3preferredEan`, `definitionsdetailsData3sapAssortmentLevel`, 
           `definitionsdetailsData3sapPrice`, `definitionsdetailsData3season`, `definitionsdetailsData3showOnLineSku`, 
           `definitionsdetailsData3size_code`, `definitionsdetailsData3size_description`, `definitionsdetailsData3skuID`, 
           `definitionsdetailsData3skuName`, `definitionsdetailsData3stateOfArticle`, `definitionsdetailsData3umSAPprice`,
            `definitionsdetailsData3volume`, `definitionsdetailsData3weight`, `definitionsheaderDatabag`,
             `definitionsheaderDatableachingDescription`, `definitionsheaderDatabrand`, `definitionsheaderDatabrandCode`,
              `definitionsheaderDatacatalog`, `definitionsheaderDatacomposition`, `definitionsheaderDatacreationDateInDatabase`,
               `definitionsheaderDatacustom1`, `definitionsheaderDatacustom2`, `definitionsheaderDatacustom3`, 
               `definitionsheaderDatadrinkHolder`, `definitionsheaderDatadryCleaningDescription`, `definitionsheaderDatadryingDescription`, 
               `definitionsheaderDataEShopDisplayName`, `definitionsheaderDataEShopLongDescription`, `definitionsheaderDataergonomicSeat`,
                `definitionsheaderDatafasteningTypeDescription`, `definitionsheaderDatafasteningTypeTextile`, `definitionsheaderDataflat`,
                 `definitionsheaderDatafreeDelivery`, `definitionsheaderDatagender`, `definitionsheaderDataindicatorOfItHasToBeAssembled`,
                  `definitionsheaderDataironingDescription`, `definitionsheaderDatalastDateChanged`, `definitionsheaderDatalastUserChanged`,
                   `definitionsheaderDataproductFeatures0`, `definitionsheaderDataproductFeatures1`, 
                   `definitionsheaderDataproductMissingFeatures0`, `definitionsheaderDataproductMissingFeatures1`,
                    `definitionsheaderDataproductStatus`, `definitionsheaderDatapulloutType`, `definitionsheaderDatapulloutTypeDescription`, 
                    `definitionsheaderDatapunnet`, `definitionsheaderDatasapCategoryID`, `definitionsheaderDatasapCategoryName`,
                     `definitionsheaderDatasapDivisionID`, `definitionsheaderDatasapDivisionName`, `definitionsheaderDatasapFamilyDescription`,
                      `definitionsheaderDatasapFamilyID`, `definitionsheaderDatasapFamilyName`, `definitionsheaderDatasapMacrocategoryID`,
                       `definitionsheaderDatasapMacrocategoryName`, `definitionsheaderDatasapName`, `definitionsheaderDatasapUniverseID`,
                        `definitionsheaderDatasapUniverseName`, `definitionsheaderDatashowOnLine`, `definitionsheaderDatasizeGuide`, 
                        `definitionsheaderDatasourceID`, `definitionsheaderDatauserOfCreation`, `definitionsheaderDatawaistlineDescription`,
                         `definitionsheaderDatawashability`, `definitionsheaderDatawashabilityDescription`, `definitionsheaderDatazipStopper`, 
                         `definitionslocale`, `dryCleaningCode`, `dryingCode`, `fasteningTypeCode`, `ironingCode`, `productID`, 
                         `pulloutTypeCode`, `sapPacket`, `updateImages`, `waistlineCode`, `washabilityCode`)
VALUES (6, 'en_GB', 'CD01', 0.0, 0.0, 030, 'AZUL', 'false', 'true', 8052473552489, 'TB', 4.2, 'A/I', 'true', 'M00', '50 cm - 0-1 Meses',
 000000000593430001, 'CHAQUETA TRICOT ALGODOÓN AZUL / AZUL / 50 cm - 0-1 Meses', 'true', '€', 489.51, 52.0, 'CD01', 0.0, 0.0, 030, 'AZUL', 
 'false', 'false', 8052473552519, 'TB', 4.2, 'A/I', 'true', 'M06', '68 cm - 6-9 Meses', 000000000593430004, 
 'CHAQUETA TRICOT ALGODOÓN AZUL / AZUL / 68 cm - 6-9 Meses', 'true', '€', 489.51, 52.0, 'CD01', 0.0, 0.0, 030, 'AZUL',
  'false', 'false', 8052473552502, 'TB', 4.2, 'A/I', 'true', 'M03', '62 cm - 3-6 Meses', 000000000593430003,
   'CHAQUETA TRICOT ALGODOÓN AZUL / AZUL / 62 cm - 3-6 Meses', 'true', '€', 489.51, 52.0, 'CD01', 0.0, 0.0, 030, 'AZUL', 
   'false', 'false', 8052473552496, 'TB', 4.2, 'A/I', 'true', 'M01', '56 cm - 1-3 Meses', 000000000593430002,
    'CHAQUETA TRICOT ALGODOÓN AZUL / AZUL / 56 cm - 1-3 Meses', 'true', '€', 489.51, 52.0, 'false', '', 'Prénatal', 2,
     'Espain', '', '2017-01-14T02:10:56.493+01:00', '', '', '', 'false', 'Limpieza en seco con algún tipo de disolvente', '', 
     'CHAQUETA TRICOT ALGODOÓN AZUL', 'Cárdigan en tricot azul cielo de algodón con cuello redondo y cierre por botones frontales.',
      'false', '-', '-', 'false', 'true', 'Niño', 'false', '', '2017-01-14T02:10:56.493+01:00', 'pwic', 'Easy Fit Tape',
       'Special Bra', 'Easy Fit Tape', 'Special Bra', '', '', '', 'false', 03, 'R.Nacido', 0303, 'Over', 'CHAQUETA RECIÉN NACIDO',
        62, 'CHAQUETA RN', 'T02', 'MC Recién Nacido', 'CHAQUETA TRICOT ALGODON AZUL', 'T', 'U Textil', 'false', 'CT066', '', 'SAP',
         '-', '', '', 'false', 'es_ES', 6, 20, 9, 12, 000000000000593430, 4, 999, 'false', 15, 28);
UPDATE Product
SET ;
DELETE FROM Product;