array (
  'product' => 
  array (
    'bleachingCode' => '6',
    'defaultLanguage' => 'en_GB',
    'definitions' => 
    array (
      'detailsData' => 
      array (
        0 => 
        array (
          'cedi' => 'CD01',
          'childWeightFrom' => '0.0',
          'childWeightTo' => '0.0',
          'color_code' => '030',
          'color_description' => 'AZUL',
          'countryImages' => 'false',
          'defaultSku' => 'true',
          'preferredEan' => '8052473552489',
          'sapAssortmentLevel' => 'TB',
          'sapPrice' => '4.2',
          'season' => 'A/I',
          'showOnLineSku' => 'true',
          'size_code' => 'M00',
          'size_description' => '50 cm - 0-1 Meses',
          'skuID' => '000000000593430001',
          'skuName' => 'CHAQUETA TRICOT ALGODOÓN AZUL / AZUL / 50 cm - 0-1 Meses',
          'stateOfArticle' => 'true',
          'umSAPprice' => '€',
          'volume' => '489.51',
          'weight' => '52.0',
        ),
        1 => 
        array (
          'cedi' => 'CD01',
          'childWeightFrom' => '0.0',
          'childWeightTo' => '0.0',
          'color_code' => '030',
          'color_description' => 'AZUL',
          'countryImages' => 'false',
          'defaultSku' => 'false',
          'preferredEan' => '8052473552519',
          'sapAssortmentLevel' => 'TB',
          'sapPrice' => '4.2',
          'season' => 'A/I',
          'showOnLineSku' => 'true',
          'size_code' => 'M06',
          'size_description' => '68 cm - 6-9 Meses',
          'skuID' => '000000000593430004',
          'skuName' => 'CHAQUETA TRICOT ALGODOÓN AZUL / AZUL / 68 cm - 6-9 Meses',
          'stateOfArticle' => 'true',
          'umSAPprice' => '€',
          'volume' => '489.51',
          'weight' => '52.0',
        ),
        2 => 
        array (
          'cedi' => 'CD01',
          'childWeightFrom' => '0.0',
          'childWeightTo' => '0.0',
          'color_code' => '030',
          'color_description' => 'AZUL',
          'countryImages' => 'false',
          'defaultSku' => 'false',
          'preferredEan' => '8052473552502',
          'sapAssortmentLevel' => 'TB',
          'sapPrice' => '4.2',
          'season' => 'A/I',
          'showOnLineSku' => 'true',
          'size_code' => 'M03',
          'size_description' => '62 cm - 3-6 Meses',
          'skuID' => '000000000593430003',
          'skuName' => 'CHAQUETA TRICOT ALGODOÓN AZUL / AZUL / 62 cm - 3-6 Meses',
          'stateOfArticle' => 'true',
          'umSAPprice' => '€',
          'volume' => '489.51',
          'weight' => '52.0',
        ),
        3 => 
        array (
          'cedi' => 'CD01',
          'childWeightFrom' => '0.0',
          'childWeightTo' => '0.0',
          'color_code' => '030',
          'color_description' => 'AZUL',
          'countryImages' => 'false',
          'defaultSku' => 'false',
          'preferredEan' => '8052473552496',
          'sapAssortmentLevel' => 'TB',
          'sapPrice' => '4.2',
          'season' => 'A/I',
          'showOnLineSku' => 'true',
          'size_code' => 'M01',
          'size_description' => '56 cm - 1-3 Meses',
          'skuID' => '000000000593430002',
          'skuName' => 'CHAQUETA TRICOT ALGODOÓN AZUL / AZUL / 56 cm - 1-3 Meses',
          'stateOfArticle' => 'true',
          'umSAPprice' => '€',
          'volume' => '489.51',
          'weight' => '52.0',
        ),
      ),
      'headerData' => 
      array (
        'bag' => 'false',
        'bleachingDescription' => '',
        'brand' => 'Prénatal',
        'brandCode' => '2',
        'catalog' => 'Espain',
        'composition' => '',
        'creationDateInDatabase' => '2017-01-14T02:10:56.493+01:00',
        'custom1' => '',
        'custom2' => '',
        'custom3' => '',
        'drinkHolder' => 'false',
        'dryCleaningDescription' => 'Limpieza en seco con algún tipo de disolvente',
        'dryingDescription' => '',
        'EShopDisplayName' => 'CHAQUETA TRICOT ALGODOÓN AZUL',
        'EShopLongDescription' => 'Cárdigan en tricot azul cielo de algodón con cuello redondo y cierre por botones frontales.',
        'ergonomicSeat' => 'false',
        'fasteningTypeDescription' => '-',
        'fasteningTypeTextile' => '-',
        'flat' => 'false',
        'freeDelivery' => 'true',
        'gender' => 'Niño',
        'indicatorOfItHasToBeAssembled' => 'false',
        'ironingDescription' => '',
        'lastDateChanged' => '2017-01-14T02:10:56.493+01:00',
        'lastUserChanged' => 'pwic',
        'productFeatures' => 
        array (
          0 => 'Easy Fit Tape',
          1 => 'Special Bra',
        ),
        'productMissingFeatures' => 
        array (
          0 => 'Easy Fit Tape',
          1 => 'Special Bra',
        ),
        'productStatus' => '',
        'pulloutType' => '',
        'pulloutTypeDescription' => '',
        'punnet' => 'false',
        'sapCategoryID' => '03',
        'sapCategoryName' => 'R.Nacido',
        'sapDivisionID' => '0303',
        'sapDivisionName' => 'Over',
        'sapFamilyDescription' => 'CHAQUETA RECIÉN NACIDO',
        'sapFamilyID' => '62',
        'sapFamilyName' => 'CHAQUETA RN',
        'sapMacrocategoryID' => 'T02',
        'sapMacrocategoryName' => 'MC Recién Nacido',
        'sapName' => 'CHAQUETA TRICOT ALGODON AZUL',
        'sapUniverseID' => 'T',
        'sapUniverseName' => 'U Textil',
        'showOnLine' => 'false',
        'sizeGuide' => 'CT066',
        'sourceID' => '',
        'userOfCreation' => 'SAP',
        'waistlineDescription' => '-',
        'washability' => '',
        'washabilityDescription' => '',
        'zipStopper' => 'false',
      ),
      'locale' => 'es_ES',
    ),
    'dryCleaningCode' => '6',
    'dryingCode' => '20',
    'fasteningTypeCode' => '9',
    'ironingCode' => '12',
    'productID' => '000000000000593430',
    'pulloutTypeCode' => '4',
    'sapPacket' => '999',
    'updateImages' => 'false',
    'waistlineCode' => '15',
    'washabilityCode' => '28',
  ),
)